In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]
print(a, type(a))

[1, 2, 3, 4, 5] <class 'list'>


In [4]:
a = np.array(a)
print(a, type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [6]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [8]:
a = list(range(1, 10))
b = np.arange(1, 10)
print(a, b, sep='\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [9]:
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
a = np.linspace(0, 1, 9)
print(a)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [12]:
a = [1, 2, 3]
b = [4, 5, 6]
c = np.array([a, b])
print(c)

[[1 2 3]
 [4 5 6]]


In [13]:
print(c.shape)

(2, 3)


In [14]:
a = np.array(a)
print(a.shape)

(3,)


In [15]:
a = np.random.rand(4)
print(a)

[0.84444033 0.29696433 0.28991377 0.00744102]


In [16]:
a = np.random.rand(3, 3)
print(a)

[[9.15316537e-01 3.12184686e-01 9.33099547e-04]
 [6.14418424e-02 3.42501006e-01 6.26165262e-01]
 [9.95042804e-01 1.98521277e-01 4.43617194e-01]]


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * 2)
print(b / 2)

[5 7 9]
[-3 -3 -3]
[2 4 6]
[2.  2.5 3. ]


In [18]:
print(a * b)

[ 4 10 18]


In [19]:
a = np.array([[1, 1],
              [0, 1]])
b = np.array([[2, 0],
              [3, 4]])
print(a * b)

[[2 0]
 [0 4]]


In [20]:
print(a @ b)

[[5 4]
 [3 4]]


In [21]:
print(a.dtype)

int64


In [22]:
a = np.zeros(5)
b = np.zeros(5, dtype=int)
print(a, b, sep='\n')

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [23]:
print(a.size, a.shape)

5 (5,)


In [24]:
a = np.array([[1, 1],
              [0, 1]])
print(a.size, a.shape)

4 (2, 2)


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = 2*a - 3*b
print(c)

[-10 -11 -12]


In [26]:
a = np.linspace(0, 1, 20)
print(a)

print(np.sin(a))
print(np.cos(a))
print(np.sqrt(a))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[0.         0.05260728 0.10506887 0.15723948 0.20897462 0.26013102
 0.310567   0.36014289 0.40872137 0.45616793 0.50235115 0.54714315
 0.59041986 0.63206143 0.67195255 0.70998273 0.74604665 0.78004444
 0.81188195 0.84147098]
[1.         0.99861528 0.99446495 0.9875605  0.97792106 0.96557333
 0.95055149 0.93289715 0.91265921 0.88989371 0.8646637  0.83703905
 0.80709627 0.77491828 0.7405942  0.70421909 0.66589368 0.62572411
 0.58382164 0.54030231]
[0.         0.22941573 0.32444284 0.39735971 0.45883147 0.51298918
 0.56195149 0.60697698 0.64888568 0.6882472  0.72547625 0.76088591
 0.79471941 0.82717019 0.85839508 0.88852332 0.91766294 0.9459053
 0.97332853 1.        ]


In [27]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [28]:
a = np.array(a)
b = np.array(b)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [30]:
a = np.ones((2,3))
b = 2 * np.ones((2, 3))
print(a)
print(b)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]


In [31]:
print(a.shape)

(2, 3)


In [33]:
a = a.reshape(3, 2)
print(a)
print(a.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


In [34]:
a = np.array([1, 2, 3])
b = a.reshape(3, 1)
c = a.reshape(1, 3)
print(a, b, c, sep='\n')

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]


In [35]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(3, 1)
(1, 3)


In [36]:
a = np.array([1, 2, 3])
b = a # shallow copy
print(a)
print(b)

[1 2 3]
[1 2 3]


In [37]:
b[0] = 100
print(a, b, sep='\n')

[100   2   3]
[100   2   3]


In [38]:
c = a.copy()  # deep copy
a[0] = 1
print(a, b, c, sep='\n')

[1 2 3]
[1 2 3]
[100   2   3]


In [40]:
a = np.linspace(1, 25, 25)
print(a)
a = a.reshape(5, 5)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [42]:
print(a[0, 0])
print(a[1, 0])

1.0
6.0


In [43]:
print(a[1:4])

[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [44]:
print(a[:, :2])

[[ 1.  2.]
 [ 6.  7.]
 [11. 12.]
 [16. 17.]
 [21. 22.]]


In [45]:
print(a[1:4, :])

[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [46]:
print(a[1:4, 1:4])

[[ 7.  8.  9.]
 [12. 13. 14.]
 [17. 18. 19.]]


In [47]:
print(a[1:4, 2:4])

[[ 8.  9.]
 [13. 14.]
 [18. 19.]]


In [49]:
a = 100 * np.random.rand(10)
print(a)

[11.05346029 47.32366106 51.97033118 58.58651647 86.59888781  6.6511773
 40.2074327  23.6688709  18.62835875 37.47366575]


In [50]:
print(a > 50)

[False False  True  True  True False False False False False]


In [51]:
b = a[a > 50] # boolean indexing
print(b)

[51.97033118 58.58651647 86.59888781]


In [53]:
import random as rd
a = np.array(rd.sample(range(100), 20))
print(a)

[ 9 91 12 24 71 36 93 78 66 70 58  7 89 88 18 53 57 95 87 69]


In [54]:
evens = a[a%2 == 0]
print(evens)

[12 24 36 78 66 70 58 88 18]


In [55]:
odds = a[a%2 == 1]
print(odds)

[ 9 91 71 93  7 89 53 57 95 87 69]


In [56]:
a = np.array(rd.sample(range(-100, 100), 20))
print(a)

[ 51 -97  49   9 -88 -87 -16 -77  57  42 -30 -54 -82 -79  18  -6  29 -36
  27   2]


In [59]:
# Lọc các số âm
negatives = a[a < 0]
print(negatives)
# Lọc các số dương
positives = a[a > 0]
print(positives)

[-97 -88 -87 -16 -77 -30 -54 -82 -79  -6 -36]
[51 49  9 57 42 18 29 27  2]


In [61]:
a = 100 * np.random.rand(20)
print(a)
print(max(a), min(a), sum(a), sum(a) / a.size, sep='\n')

[58.70128352 58.33137231 57.97928632 41.61175168 19.20597204 63.16654228
 16.40189439 50.81275699 73.393329   21.47061989 25.33636222 58.00042343
 56.62270241 90.18663847  5.29959404 39.01708414 98.61962078  7.28774188
 86.70459061 19.39218625]
98.6196207766186
5.299594040458333
947.5417526454075
47.377087632270374


In [62]:
# Chuẩn hóa a về khoảng [0, 1]
m = max(a)
b = a / m
print(b)

[0.59522926 0.59147837 0.58790823 0.42194192 0.19474798 0.64050685
 0.16631472 0.51523983 0.74420616 0.21771144 0.25690995 0.58812256
 0.57415251 0.91448981 0.05373772 0.39563206 1.         0.07389748
 0.87918195 0.19663619]


In [66]:
# standard scaler => trung bình = 0 và độ lệch chuẩn (std) = 1
s = np.std(a)
m = np.mean(a)
c = (a - m) / s
print(c)
print(np.mean(c), np.std(c))

[ 0.41804055  0.40438502  0.39138752 -0.21283138 -1.03995628  0.58287867
 -1.14347075  0.12683012  0.9604076  -0.95635523 -0.81364867  0.39216781
  0.34130828  1.58034427 -1.55331987 -0.30861533  1.89165367 -1.47992602
  1.45180206 -1.03308205]
2.997602166487923e-16 1.0


In [67]:
d = (a - a.min()) / (a.max() - a.min())
print(d)

[0.57224254 0.56827864 0.56450576 0.38911431 0.14901815 0.62009142
 0.11897018 0.48771056 0.72967976 0.1732857  0.21471027 0.56473226
 0.54996886 0.90963373 0.         0.36131033 1.         0.02130462
 0.87232076 0.15101359]


In [69]:
m1 = a.min()
m2 = a.max()
e = (a - m1) / (m2 - m1)
print(e)

[0.57224254 0.56827864 0.56450576 0.38911431 0.14901815 0.62009142
 0.11897018 0.48771056 0.72967976 0.1732857  0.21471027 0.56473226
 0.54996886 0.90963373 0.         0.36131033 1.         0.02130462
 0.87232076 0.15101359]
